version: '3.8'
services:
  db:
    image: mysql:8.0.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: walletapplication
    ports:
      - "3306:3306"

  walletapplication:
    build: .
    container_name: walletapplication
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - JDBC_URL=jdbc:mysql://db:3306/walletapplication